#pragma once
#include "framework.h"
#include "resource.h"
#include <Windows.h>
#include <objidl.h> 
#include <gdiplus.h>
#include "ChessBoard.h"
#include "ChessGame.h"
#include "ChessBoardWindow.h"
#include <windowsx.h>